---
name: Create packages and test installation

on:
  pull_request:

jobs:
  centos7:
    name: Build CentOS 7 RPMs
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms7
          path: |
            build/RPMS/x86_64/ui-*.el7.x86_64.rpm

  centos8:
    name: Build CentOS 8 RPMs
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.epel.cloud|g' /etc/yum.repos.d/CentOS-Linux-*
          yum install -y rpm-build rpmlint make rsync
      - name: build rpm
        run: |
          make rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload rpms
        uses: actions/upload-artifact@v3
        with:
          name: rpms8
          path: |
            build/RPMS/x86_64/ui-*.el8.x86_64.rpm

  centos7-install:
    name: Install CentOS 7 rpms
    needs: centos7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms7
      - name: Install generated rpms
        run: |
          yum localinstall -y ui-*.rpm

  # XXX dependencies taken from non default repositories
  centos8-install:
    name: Install CentOS 8 rpms
    needs: centos8
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8
      - name: Install generated rpms
        run: |
          sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.epel.cloud|g' /etc/yum.repos.d/CentOS-Linux-*
          yum localinstall -y ui-*.rpm
