---
name: Create packages and test installation

on:
  pull_request:

jobs:
  # Use a matrix for AlmaLinux version
  build-almalinux:
    strategy:
      matrix:
        almalinux-version: [8, 9]
    name: Build AlmaLinux ${{ matrix.almalinux-version }} RPMs
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y rpm-build rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
          rpmlint --file .rpmlint.ini build/RPMS/x86_64/*.rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms${{ matrix.almalinux-version }}
          path: |
            build/RPMS/x86_64/ui-*.el${{ matrix.almalinux-version }}.x86_64.rpm

  install-almalinux8:
    name: Install AlmaLinux 8 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:8
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms8
      - name: Install generated RPMs
        run: |
          dnf install -y epel-release
          dnf config-manager --add-repo http://repository.egi.eu/sw/production/cas/1/current/repo-files/egi-trustanchors.repo
          # FIXME: Remove htcondor and replace WLCG repo by UMD5 once available
          dnf install -y https://linuxsoft.cern.ch/wlcg/el8/x86_64/wlcg-repo-1.0.0-1.el8.noarch.rpm
          dnf install -y https://research.cs.wisc.edu/htcondor/repo/23.x/htcondor-release-current.el8.noarch.rpm
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf config-manager --set-enabled powertools
          dnf localinstall -y ui-*.rpm

  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          dnf install -y epel-release
          dnf config-manager --add-repo http://repository.egi.eu/sw/production/cas/1/current/repo-files/egi-trustanchors.repo
          # FIXME: Remove htcondor and replace WLCG repo by UMD5 once available
          dnf install -y https://linuxsoft.cern.ch/wlcg/el9/x86_64/wlcg-repo-1.0.0-1.el9.noarch.rpm
          dnf install -y https://research.cs.wisc.edu/htcondor/repo/23.x/htcondor-release-current.el9.noarch.rpm
          dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          dnf config-manager --set-enabled crb
          dnf localinstall -y ui-*.rpm
